// import Head from "next/head";
// import Link from "next/link";
// import React from "react";
// import Project from "./projects/pro";

// const Projects = () => {
//     return (
//         <>
//             <Head>
//                 <title>My Portfolio | My Work</title>
//                 <meta name="description" content="Generated by create next app" />
//                 <meta name="viewport" content="width=device-width, initial-scale=1" />
//                 <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <div className=" grid md:grid-cols-2 sm:grid-cols-1 container gap-6 md:px-20 lg:px-48 xl:px-48 2xl:px-48 w-full  bg-slate-900 text-xl text-sky-400/50  p-12">
//                 <div className=" h-fit p-4 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 ">
//                     <img src="/images/projects/barista.jpg" alt="Barista Project" className="transition-all rounded-3xl duration-300 blur-sm hover:blur-none"/>
//                     <h1 className="p-4">-Barista</h1>
//                     <h1 className="p-4 text-sm text-white">-Python</h1>
//                     <Link href="">
//                     <svg xmlns="http://www.w3.org/2000/svg" width="50" height="40" fill="default" className="bi bi-github " viewBox="0 1 10 17">
//                         <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
//                     </svg>
//                     </Link>
//                     <Link href="">
//                     <svg xmlns="http://www.w3.org/2000/svg" width="30" height="40" fill="default" className="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
//                       <path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z"/>
//                       <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z"/>
//                     </svg>
//                     </Link>
//                 </div>


//                 <div className="flex-1 p-4  h-fit ax-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
//                   <div className="h-fit">
//                   <img src="/images/projects/e-shop.png" alt="E-Commerce Shop & Admin Section Project" className="transition-all rounded-3xl duration-300 blur-sm hover:blur-none"/>
//                     <h1 className="p-4">-E-Commerce Shop & Admin Section</h1>
//                     <h1 className="p-4 text-sm text-white">-Django, Python, Css, Html</h1>
//                     <Link href="">
//                     <svg xmlns="http://www.w3.org/2000/svg" width="50" height="40" fill="default" className="bi bi-github " viewBox="0 1 10 17">
//                         <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
//                     </svg>
//                     </Link>
//                     <Link href="">
//                     <svg xmlns="http://www.w3.org/2000/svg" width="30" height="40" fill="default" className="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
//                       <path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z"/>
//                       <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z"/>
//                     </svg>
//                     </Link>
//                   </div>
//                 </div>
//             </div>


//             <div className="grid md:grid-cols-2 sm:grid-cols-1 container gap-6 md:px-20 lg:px-48 xl:px-48 2xl:px-48 w-full h-auto max-w-full bg-slate-900 text-xl text-sky-400/50 align-middle p-12">
//                 <div className=" h-fit p-4 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
//                     <img src="/images/projects/contact-page.png" alt="Contact Form Project" className="transition-all rounded-3xl duration-300 blur-sm hover:blur-none"/>
//                     <h1 className="p-4">-Contact Form</h1>
//                     <h1 className="p-4 text-sm text-white">-NextJs, Javascript, Tailwind</h1>
//                     <Link href="https://github.com/MulhamShaker/Contact-page">
//                     <svg xmlns="http://www.w3.org/2000/svg" width="50" height="40" fill="default" className="bi bi-github " viewBox="0 1 10 17">
//                         <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
//                     </svg>
//                     </Link>
//                     <Link href="https://sign-form-up.vercel.app/">
//                     <svg xmlns="http://www.w3.org/2000/svg" width="30" height="40" fill="default" className="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
//                       <path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z"/>
//                       <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z"/>
//                     </svg>
//                     </Link>
//                 </div>


//                 <div className="flex-1 p-4 ax-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
//                   <div className=" h-fit">
//                   <img src="" alt="" className="transition-all rounded-full duration-300 blur-sm hover:blur-none"/>
//                     <h1 className="p-4">-</h1>
//                     <h1 className="p-4 text-sm text-white">-</h1>
//                     <Link href="">
//                     <svg xmlns="http://www.w3.org/2000/svg" width="50" height="40" fill="default" className="bi bi-github " viewBox="0 1 10 17">
//                         <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
//                     </svg>
//                     </Link>
//                     <Link href="">
//                     <svg xmlns="http://www.w3.org/2000/svg" width="30" height="40" fill="default" className="bi bi-box-arrow-up-right" viewBox="0 0 16 16">
//                       <path fill-rule="evenodd" d="M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z"/>
//                       <path fill-rule="evenodd" d="M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z"/>
//                     </svg>
//                     </Link>
//                   </div>
//                 </div>
//                 </div>
                
//                 <div>
//                 <Project />
//                 </div>
//         </>
//     );
// }

// export default Projects;




import React from 'react'
import { motion } from 'framer-motion'
import Featured from '@/components/projects/Featured'
import ProjectCard from '@/components/projects/ProjectCard'
import { fadeTop,fadeLeft , motionStep } from '@/config/motion' 
import { projects } from '@/config/projectsConfig' 
import { ProjectTypes } from '@/config/types'


const Projects = () => {
  return (
    <section id='works' >

        <motion.h1 variants={fadeLeft} {...motionStep} className='flex items-center gap-2 text-3xl font-medium text-slate-300 mb-12 mt-20' > 
        </motion.h1>

        <div className='space-y-20' >
          {projects.filter((e: ProjectTypes) => e.featured == true).map((e: ProjectTypes, i: number) => (
            <motion.div key={i} variants={fadeTop} {...motionStep} >
              <Featured {...e} secondary={i % 2 === 0 ? false : true} />
            </motion.div>
          ))} 
        </div>

        <div className='grid grid-cols-12 gap-6 gap-y-8 my-20' >
          {projects.filter((e: ProjectTypes) => e.featured !== true).map((e: ProjectTypes, i: number) => (
            <ProjectCard {...e} key={i} />
          ))} 
        </div>

    </section>
  )
}

export default Projects